
server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///graduationdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
alipay:
  appId: 9021000134698894
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCr1S+OCLWys2XBWz31C09ciJIf4Vzdw5/ESVinPQ36EozXdHhzIkRSddV1HWr6aagS5oExqZONsAXTSjv0MYdVF8ZFn+i2gm3CxMXpHzGLgjwGRN+ZPW9aXayDml1utAhJ3Cq0Xu7YkJnIurGL8vs+YVT6++4d2u5gU2Tm/krynvZvRGcgu74oauKfDTOg6loo2ld+vWOsVS125FQYeMDkS9aa8/bFD30xVn/nLrbB6d1BIivmcNy/sVq6T6IquztSia0CsZixDO8qeR6h9i2f1br27CdHatdnC6QEGjd6Hjo8tq1FBYgD4diXKmg9HubVz8209+9m83MDDP563qmpAgMBAAECggEAf82IGTQRMGCOBko+wssus7xAMsYDtE2TvwJulbSreJvjdTyDed66wjoyEXFX5/g9shEPdkiSHogVTRmhjfZombmdFpvhEh3gVUTVjpZM2156Fo+TXv56m9OgRCHD7Fqq74R5nr4dF6Y1Oz7gXx7SD4uFEUffywTS14IvQj9QrzKkRFDB3d7/fMqBGk/yJaPPEWB1p43w1jl0qdH5Vn8nDPm/fSOyaX4QcL5wCxmVwYvb6XZZNo0Ie0jXdAueM3ACdK5Fkr3IYLIaTgotTn9VYYOJQMpEEQxIZRmmfO4AHXgO8g8JvOf5TTmFaW7thZUAcMJJhBx4EKtzGkO2zHo/oQKBgQDUPu8pQ9ZOgBePE7MuFzXcf4t7v0gLtx9ywKXR3gt+fZnLRqB9hzE3Q8tY+AkyHfIwJXkLUblx7ssVKCK7jtxMtM9k0W680DjXE2oIm8QQuKS8SyZMNeVzhn9lpPnqXZwdl2RIYHiOP3NjJu2TLjc02LP1ywIz6O3Wt/T9ntzDYwKBgQDPQX2rh8S4UwYSL1/Wno4wqW/C9W3noPT36UIQPOczdsh/wo7NPspDf00MlRlUQ6jeXTwgDQ7Qfd68kzWrlQgeR2yVaVWKFQpnf5yeUZbNsxZib1YRto5KMs2kj4EeysmOlJw8v1DnK0/71Iw0c5pQMETsLHscBEjmQKNc6gj6gwKBgDbZLKTVSwRuRahLxvoaNWkN7NXF0LB2WkIlVrStVPsTKjNFxSOrVCSb+Gi9cGLrKjMW+/jY3bt7oi+Nd6xQds27y/yZwqw4gvfRpI0k873+eVPPd84p/2mjUDjMMWlHV5iuDtRFWeIos4DkBnEKeGnHtnnGRIN1pkDeuQjxjMtRAoGADhaum0VsavdB12SfCDDZC5fJACC86tz3Kg8SLZZmRQpTENRB7tPQ3gu+SheslBzRUuRVnPwmQKf9xyXepR5JYf2K9REm/m71uRlkpSJ4tNzyrZhR6nxVadfQQNp8dYJldyrFACAlOMGp+z10lnAxUjglx0QyzjHAXt6P/FXwbE8CgYEAyQDdb2ReOwt81wD2io4Z32+aCUYFOOeItwnsxG0Zw9c6oKggewMw+N3bsfORRnJBLEVQa1vmPKWvO5vAiads18x1dCSjOqDjSS6u8Phsjle7d3RaQcFcRsFAR6MpRi+inWmsYOMxWe/rf+zC1Nz4fSAtZsvivmd820NNZDFMP3s=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj79OW6ksKDap0sctlJJaAtCjHkObnoOq+bXjt0OXWu9lY94IFWQ1z4HuXjy4GqBKB4Qn3y7LyGFHgKq6veyXUGSYPyIX15yrmP6fssoR4pAAAf9OLG6PrF+lLx42GpP+f6EHgXgqgrLhcq5zzBw0sNg+5UuU6BrbXCxRyqshp5FMHYVIeYV3K5+5av2rQzEn0Di12ox1s+aVU5M3pWc21ds+sYgDOU6xzUXH1vQ+ui8naGMIojzKG6b8bA0p0Em6Gft86BWowSigRNm8SneOM99PeRHn+aesHKpyCGGXUSkINA7tFj49alShStrFdOdRYZyynlGvExMnQX1Blr5T5QIDAQAB
#  http://9g63jg.natappfree.cc为公网地址  alipay/notify 为配置的接口
  notifyUrl: http://9g63jg.natappfree.cc/alipay/notify
logging:
  level:
    com.example.graduationproject.mapper: debug


