
server:
  port: 8888
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///graduationdb
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost


